# Generated by Django 6.0.7 on 2026-07-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_application", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="From",
            new_name="Form",
        ),
    ]
